name: Publish to PyPI

on:
  push:
    tags:
      - "**"
jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - name: Publish
        run: uv build && uv publish
