name: Publish to PyPi

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: master
    types: completed
jobs:
  build-n-publish:
    name: Build and publish
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - name: publish
        run: pdm publish
